const broadcastMockData = [
	{
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, {
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, {
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, {
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, {
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, { 
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, { 
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, {
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, {
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, {
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, {
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, {
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}, { 
		'batchName': 'First broadcast',
		'accounts': '1188, 1234, 5678',
		'notificationEmails': 'marmstrong@ciswired.com',
		'frequency': 'Weekly',
		'runsOn': 'Monday',
		'startsOn': 'Sunday',
		'lastRun': '08/08/2018',
		'nextRun': '08/15/2018',
		'runStatus': 'Okay',
	}
]

export default broadcastMockData